---
- hosts: all
  tasks:
  - name: ensure packages required for node install are installed
    apt: update_cache=yes pkg={{ item }} state=present
    sudo: yes
    with_items:
        - python-software-properties
        - python
        - g++
        - make
        - python-pycurl 
        - git
  - name: ensure nodejs custom repository is installed
    apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu raring main' state=present
    sudo: true
  - name: ensure nodejs and npm is installed
    apt: update_cache=yes pkg=nodejs state=present force=yes
    sudo: yes
  - name: Install "yeoman" node.js package globally.
    npm: name=yo global=yes
    sudo: yes
  - name: Install packages based on local package.json.
    npm: path=/vagrant/yeoman
  - name: ensure ruby for compass is installed
    apt: update_cache=yes pkg=ruby state=present
    sudo: yes
  - name : ensure compass is installed
    gem: name=compass state=present user_install=no
    sudo: true
  - name: ensure backend lamp packages are installed
    apt: pkg={{ item }} state=present
    sudo: yes
    with_items:
        - mysql-server
        - lighttpd
        - php5-cgi
        - php5-mysql
        - php5-cli